---
title: "Plotly example"
output: 
  html_document:
    toc: true
    toc_float: true
---


# exmaple of plotly

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

#loading data
```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb %>%
  mutate(rating = review_scores_location/2) %>%
  select(neighbourhood_group,neighbourhood,rating,price,room_type,lat,long) %>%
       filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
           
```
 
#plotly plots

## scatterplot

#type mode: geom line or geom point 
 
```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% #\n means start another line
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```
 
#boxplot

 
```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```


#barplot
```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% #n represent number of count
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```


 
 